[tool.poetry]
name = "langc"
version = "0.0.1"
description = ""
authors = ["Erick Friis <erick@langchain.dev>"]
readme = "README.md"
include = [
    {path="project_template/**/*", format="wheel"},
    {path="package_template/**/*", format="wheel"}
]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
typer = "^0.9.0"
tomli = "^2.0.1"
gitpython = "^3.1.40"
langserve = {git = "https://github.com/langchain-ai/langserve", rev = "erick/add-package-routes"}
fastapi = "^0.104.0"
uvicorn = "^0.23.2"

[tool.poetry.scripts]
langchain = "langc.cli:app"


[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.1"
pytest = "^7.4.2"
pytest-watch = "^4.2.0"

[tool.poe.tasks]
test = "poetry run pytest"
watch = "poetry run ptw"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
