[tool.poetry]
name = "langservehub-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sse-starlette = "^1.6.5"
tomli-w = "^1.0.0"
uvicorn = "^0.23.2"
fastapi = "^0.103.2"
langserve = {git = "https://github.com/langchain-ai/langserve"}

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.1"
uvicorn = "^0.23.2"
pygithub = "^2.1.1"

[tool.poe.tasks.start]
cmd="poetry run uvicorn app.server:app --reload --port $port --host $host"
args = [
    {name = "port", help = "port to run on", default = "8000"},
    {name = "host", help = "host to run on", default = "127.0.0.1"}
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
